Elastic PostProcessor Fix - library conflicts with flink-cos-hadoop
Dagger having elastic search postprocessors enabled where failing with
below error.
java.lang.NoSuchMethodError: org.apache.http.impl.auth.HttpAuthenticator.<init>(Lorg/apache/commons/logging/Log;)V

```
switched from INITIALIZING to FAILED with failure cause: java.lang.NoSuchMethodError: org.apache.http.impl.auth.HttpAuthenticator.<init>(Lorg/apache/commons/logging/Log;)V
2025-06-17T15:53:16.275408978+08:00     at org.apache.http.impl.nio.client.MainClientExec.<init>(MainClientExec.java:111)
2025-06-17T15:53:16.275415398+08:00     at org.apache.http.impl.nio.client.HttpAsyncClientBuilder.build(HttpAsyncClientBuilder.java:847)
2025-06-17T15:53:16.275420938+08:00     at org.elasticsearch.client.RestClientBuilder$2.run(RestClientBuilder.java:240)
2025-06-17T15:53:16.275425208+08:00     at org.elasticsearch.client.RestClientBuilder$2.run(RestClientBuilder.java:237)
2025-06-17T15:53:16.275429788+08:00     at java.security.AccessController.doPrivileged(Native Method)
2025-06-17T15:53:16.275433797+08:00     at org.elasticsearch.client.RestClientBuilder.createHttpClient(RestClientBuilder.java:237)
2025-06-17T15:53:16.275437608+08:00     at org.elasticsearch.client.RestClientBuilder.access$000(RestClientBuilder.java:42)
2025-06-17T15:53:16.275441468+08:00     at org.elasticsearch.client.RestClientBuilder$1.run(RestClientBuilder.java:208)
2025-06-17T15:53:16.275450327+08:00     at org.elasticsearch.client.RestClientBuilder$1.run(RestClientBuilder.java:205)
2025-06-17T15:53:16.275454317+08:00     at java.security.AccessController.doPrivileged(Native Method)
2025-06-17T15:53:16.275458507+08:00     at org.elasticsearch.client.RestClientBuilder.build(RestClientBuilder.java:205)
2025-06-17T15:53:16.275462957+08:00     at com.gotocompany.dagger.core.processors.external.es.EsAsyncConnector.createClient(EsAsyncConnector.java:73)
2025-06-17T15:53:16.275466727+08:00     at com.gotocompany.dagger.core.processors.external.AsyncConnector.open(AsyncConnector.java:154)
2025-06-17T15:53:16.275471097+08:00     at org.apache.flink.api.common.functions.util.FunctionUtils.openFunction(FunctionUtils.java:34)
2025-06-17T15:53:16.275474887+08:00     at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.open(AbstractUdfStreamOperator.java:100)
2025-06-17T15:53:16.275479016+08:00     at org.apache.flink.streaming.api.operators.async.AsyncWaitOperator.open(AsyncWaitOperator.java:163)
2025-06-17T15:53:16.275486036+08:00     at org.apache.flink.streaming.runtime.tasks.RegularOperatorChain.initializeStateAndOpenOperators(RegularOperatorChain.java:110)
2025-06-17T15:53:16.275490146+08:00     at org.apache.flink.streaming.runtime.tasks.StreamTask.restoreGates(StreamTask.java:711)
2025-06-17T15:53:16.275494246+08:00     at org.apache.flink.streaming.runtime.tasks.StreamTaskActionExecutor$1.call(StreamTaskActionExecutor.java:55)
2025-06-17T15:53:16.275498196+08:00     at org.apache.flink.streaming.runtime.tasks.StreamTask.restoreInternal(StreamTask.java:687)
2025-06-17T15:53:16.275502106+08:00     at org.apache.flink.streaming.runtime.tasks.StreamTask.restore(StreamTask.java:654)
2025-06-17T15:53:16.275506126+08:00     at org.apache.flink.runtime.taskmanager.Task.runWithSystemExitMonitoring(Task.java:958)
2025-06-17T15:53:16.275510036+08:00     at org.apache.flink.runtime.taskmanager.Task.restoreAndInvoke(Task.java:927)
2025-06-17T15:53:16.275513886+08:00     at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:766)
2025-06-17T15:53:16.275517746+08:00     at org.apache.flink.runtime.taskmanager.Task.run(Task.java:575)
2025-06-17T15:53:16.275522166+08:00     at java.lang.Thread.run(Thread.java:750)
```

cause: the expected constructor is missing because a shaded version of org.apache.commons.logging.Log is on the classpath, while the unshaded version is expected by the ES client.
https://github.com/tencentyun/flink-cos-fs/blob/4c14a02de0e15ec608e02dac202d3bbbf91ef313/flink-fs-hadoop-shaded/pom.xml#L20

Even though those are "shaded" and "internal", some of their transitive classes (e.g., Log) may leak into the classpath at runtime or clash during classloading.
From Intellij Error:
Required type: org.apache.flink.fs.shaded.hadoop3.org.apache.commons.logging.Log
Provided: org.apache.commons.logging.Log

Solution: Thanks to Flink plugins feature - https://nightlies.apache.org/flink/flink-docs-master/docs/deployment/filesystems/plugins/
tldr; Plugins uses its own classloaders for each plugin  which isolates all the
dependencies, shaded dependencies and avoids the above kind of problem.